'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8806
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Nano.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property acroread() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("acroread", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property act_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("act_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Address_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Address-Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Alterar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alterar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Alterar_12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alterar_12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Alterar_18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alterar_18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Antique_cash_register() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Antique_cash_register", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property anydesk33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anydesk33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property apply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property apply18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apply18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property apply50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apply50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property attach() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attach", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property attach24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attach24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property audi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("audi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Avancar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Avancar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aviso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aviso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property baloon1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baloon1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property banknote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("banknote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bar_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bar_chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Barril26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barril26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property beautiful_flower___Cópia_Layer_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beautiful_flower - Cópia_Layer 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bin__with_item_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bin (with item)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bin__with_item_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bin (with item)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bin24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bin24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Blac() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blac", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Blac2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blac2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blockdevice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockdevice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blockdevice50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blockdevice50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bmv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BMW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BMW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property business() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cabri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cabri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CabrioletRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CabrioletRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cadastros24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cadastros24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cadastross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cadastross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cadeado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadeado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cal_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cal 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CalcelPag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CalcelPag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calculator2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calculator2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CancelPagamento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CancelPagamento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CapaLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CapaLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cara() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cara", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Carro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carrro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carrro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cash_register() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cash_register", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cash_registerx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cash_registerx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Certo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Certo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chartBar___Cópia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chartBar - Cópia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chartPieTra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chartPieTra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cifrao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cifrao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property citroen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("citroen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cli_ente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cli_ente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cliente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cliente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property closed_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closed folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property coins_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coins 24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comando_Fechar_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comando_Fechar_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comando_Fechar50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comando_Fechar50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comando_Gravar_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comando_Gravar_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comando_Limpar_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comando_Limpar_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property commerce() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("commerce", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConcredDeb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ConcredDeb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Contato() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contato", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Contato2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contato2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Contatos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contatos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Copo_40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copo 40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property credit_card() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("credit_card", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property credit_card1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("credit_card1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property credit_card24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("credit_card24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property credit_card68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("credit_card68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property db_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property db_add2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db_add2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DBSQL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DBSQL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diagram() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diagram", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Dinamo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dinamo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Download_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ducati_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ducati-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property emoticon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emoticon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Enveloppe_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enveloppe Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Enviar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enviar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Erro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excel8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exportar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exportar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FaltaEstoque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FaltaEstoque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fiat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fiat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Files() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Files", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ford() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ford", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fornecedor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fornecedor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fornecedor24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fornecedor24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property funcio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("funcio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FUNDO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FUNDO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fundo_Nano_Automotivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fundo_Nano_Automotivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fundo_Padrao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fundo_Padrao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FundoLogin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FundoLogin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g0dkill3rBE_computer_104() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g0dkill3rBE_computer_104", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Gaveta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gaveta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Giro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Giro18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giro18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Giro24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giro24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property graficos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graficos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Honda_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Honda-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HTTP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HTTP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hyperlink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hyperlink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hyundai() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hyundai", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icons8_filtro_100__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-filtro-100 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icontexto_webdev_ok_128x128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icontexto-webdev-ok-128x128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imaginary() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imaginary", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Impressora() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Impressora", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Impressora50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Impressora50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Inadimplente24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inadimplente24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Inadimplente36x36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inadimplente36x36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoice_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoice 24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Isento36x36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Isento36x36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Itens() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Itens", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Itens_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Itens 24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jaguar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jaguar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kawasaki_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kawasaki-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kghostview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kghostview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kpersonalizer18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kpersonalizer18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kwin18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kwin18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lanche() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lanche", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property last_summer_rays() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last_summer_rays", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lilian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lilian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property line_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("line_chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Linha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Linha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property linha___Cópia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("linha - Cópia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Log_Off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Log Off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LOGIN2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGIN2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_chevrolet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_chevrolet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_dafra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_dafra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_kia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_kia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_suzuki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo-suzuki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Logo_Volkswagen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo_Volkswagen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logoEra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoEra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logoEra2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoEra2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logoOpaf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logoOpaf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogoSiteKasinski() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoSiteKasinski", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogotipoEra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogotipoEra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LogotipoEra1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogotipoEra1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lupa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lupa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lupa_Azul_12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lupa_Azul_12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Lupa_Produto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lupa_Produto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lupa18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lupa18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mail_icon24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mail_icon24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mazda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mazda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mdi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mDI1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mDI1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mecanico50x50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mecanico50x50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MenuFiscal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuFiscal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mercedes_Benz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mercedes-Benz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mitsubishi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mitsubishi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property motorcycle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("motorcycle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nano() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nano", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NANO_COMMERCE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NANO-COMMERCE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NANOAutomotivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NANOAutomotivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NanoMail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NanoMail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NanoMailVermelho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NanoMailVermelho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NanoMaiVerde() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NanoMaiVerde", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NanoWEb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NanoWEb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NFe_Baixar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NFe_Baixar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NFe_Carregando() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NFe_Carregando", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Nfe32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nfe32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NFe36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NFe36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NFse36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NFse36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property notepad24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notepad24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OS18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OS18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Papier2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Papier2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pedido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pedido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pedido_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pedido 36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pedido2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pedido2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Peugeot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Peugeot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phone_icon24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone_icon24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Phone2___Cópia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Phone2 - Cópia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playlist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playlist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playlist50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playlist50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property porcentagem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("porcentagem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Porcentagem2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Porcentagem2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property porcentagem68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("porcentagem68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property postit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("postit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Prevew() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Prevew", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Print24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prodto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prodto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Produto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Produto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Prospeccao_clientes_porcentagem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Prospeccao_clientes_porcentagem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property R1Studio_Black_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("R1Studio_Black_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property randr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("randr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property randr24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("randr24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Receber() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Receber", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reminders() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reminders", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reminders24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reminders24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Remove_Item() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remove Item", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property renault() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("renault", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Revisao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Revisao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property salada40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salada40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sangria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sangria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Senha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Senha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sent_Mail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sent Mail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property showmypc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("showmypc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Shutdown_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shutdown 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Skype_icon24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skype_icon24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sorvete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sorvete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spellcheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spellcheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQL_Management_Studio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQL-Management-Studio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQL2008() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQL2008", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property suporte() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suporte", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Suprimento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Suprimento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TeamViwer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TeamViwer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tela___Cópia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tela - Cópia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TelaLogin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TelaLogin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Texto36x36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Texto36x36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Total() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Total", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Truck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Truck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Userar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Userar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Usu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Usu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vendedora1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vendedora1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vendedora2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vendedora2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vendedora3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vendedora3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vendedora4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vendedora4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property viewmag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewmag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property viewmag18x18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewmag18x18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property violet1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("violet1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property violet2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("violet2_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property violet2_Layer_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("violet2_Layer 1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Webcam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Webcam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property word8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XML() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XML", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property XML24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XML24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yamaha_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yamaha_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Zoom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zoom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
